#!/usr/bin/env bash

# Akro V2 configuration. Environment variables always win.
AKRO_ROOT="${AKRO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)}"
AKRO_DATA_DIR="${AKRO_DATA_DIR:-$HOME/.akro}"
AKRO_GLOBAL_DIR="${AKRO_GLOBAL_DIR:-$AKRO_DATA_DIR/global}"
AKRO_PROJECTS_DIR="${AKRO_PROJECTS_DIR:-$AKRO_DATA_DIR/projects}"
AKRO_STATE_FILE="${AKRO_STATE_FILE:-$AKRO_DATA_DIR/state.json}"
AKRO_SKILLS_DIR="${AKRO_SKILLS_DIR:-$AKRO_ROOT/skills}"
AKRO_RUNTIME_DIR="${AKRO_RUNTIME_DIR:-$AKRO_DATA_DIR/runtime}"

OLLAMA_API_BASE="${OLLAMA_API_BASE:-http://127.0.0.1:11434}"
OLLAMA_CHAT_URL="${OLLAMA_CHAT_URL:-$OLLAMA_API_BASE/api/chat}"
OLLAMA_TAGS_URL="${OLLAMA_TAGS_URL:-$OLLAMA_API_BASE/api/tags}"
OLLAMA_EMBED_URL="${OLLAMA_EMBED_URL:-$OLLAMA_API_BASE/api/embed}"

DEFAULT_MODEL="${DEFAULT_MODEL:-llama:latest}"
NEURON_MODEL="${NEURON_MODEL:-neuron:latest}"
LIBRARIAN_MODEL="${LIBRARIAN_MODEL:-librarian:latest}"
AKRO_EMBED_MODEL="${AKRO_EMBED_MODEL:-embeddinggemma:latest}"

CHAT_NUM_CTX="${CHAT_NUM_CTX:-16384}"
CHAT_NUM_PREDICT="${CHAT_NUM_PREDICT:-3000}"
CHAT_HISTORY_MAX_CHARS="${CHAT_HISTORY_MAX_CHARS:-18000}"
CHAT_HISTORY_MAX_MESSAGES="${CHAT_HISTORY_MAX_MESSAGES:-24}"

BRAIN_LEARN_CHUNK_CHARS="${BRAIN_LEARN_CHUNK_CHARS:-32000}"
BRAIN_MAX_NOTE_CONTEXT="${BRAIN_MAX_NOTE_CONTEXT:-4}"
BRAIN_GLOBAL_NOTE_CONTEXT="${BRAIN_GLOBAL_NOTE_CONTEXT:-2}"
BRAIN_JSON_RETRIES="${BRAIN_JSON_RETRIES:-2}"
BRAIN_MIN_IMPORTANCE="${BRAIN_MIN_IMPORTANCE:-0.15}"
BRAIN_CONTEXT_MAX_CHARS="${BRAIN_CONTEXT_MAX_CHARS:-10000}"
KNOWLEDGE_CONTEXT_MAX_CHARS="${KNOWLEDGE_CONTEXT_MAX_CHARS:-14000}"

KNOWLEDGE_CHUNK_CHARS="${KNOWLEDGE_CHUNK_CHARS:-4500}"
KNOWLEDGE_MAX_CONTEXT="${KNOWLEDGE_MAX_CONTEXT:-3}"
KNOWLEDGE_GLOBAL_CONTEXT="${KNOWLEDGE_GLOBAL_CONTEXT:-1}"
DOCUMENT_MAX_BYTES="${DOCUMENT_MAX_BYTES:-1000000}"
DOCUMENT_INLINE_BYTES="${DOCUMENT_INLINE_BYTES:-12000}"

TAVILY_API_URL="${TAVILY_API_URL:-https://api.tavily.com/search}"
TAVILY_MAX_RESULTS="${TAVILY_MAX_RESULTS:-5}"
TAVILY_API_KEY="${TAVILY_API_KEY:-}"

UI_TITLE="${UI_TITLE:-AKRO}"
AKRO_SHOW_ACTIVITY="${AKRO_SHOW_ACTIVITY:-1}"
AKRO_AUTO_LEARN="${AKRO_AUTO_LEARN:-1}"
